// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn0l4MzLIONmra8N2fgURdJgw5g7vCOW8',
    appId: '1:654637321704:web:79db8aa55d6df7b6cf685d',
    messagingSenderId: '654637321704',
    projectId: 'dkudiplome',
    authDomain: 'dkudiplome.firebaseapp.com',
    storageBucket: 'dkudiplome.appspot.com',
    measurementId: 'G-D0Q0XSNC9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1oVi6pYjoewfeT-x4IpeLq-O2tGIk2w',
    appId: '1:654637321704:android:59090f7dcfd457c6cf685d',
    messagingSenderId: '654637321704',
    projectId: 'dkudiplome',
    storageBucket: 'dkudiplome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG519pPEcAesBWaDFml11LBanLS6KkYyo',
    appId: '1:654637321704:ios:6931aa765f5f1a59cf685d',
    messagingSenderId: '654637321704',
    projectId: 'dkudiplome',
    storageBucket: 'dkudiplome.appspot.com',
    iosBundleId: 'kz.kdu.diplomeAisha',
  );
}
